(()=>{
'use strict';
const D=window.AI_COMPASS_DATA;
if(!D||!Array.isArray(D.articles))return;

const bars=(values,cls='')=>`<div class="mini-bars ${cls}">${values.map(v=>`<i style="height:${v}%"></i>`).join('')}</div>`;
const metric=(label,value,note='',tone='')=>`<i class="${tone}"><small>${label}</small><b>${value}</b><em>${note}</em></i>`;
const mock=(n,type,title,desc,metrics,detail,dark=false)=>`<figure class="dashboard-example ${type}"><figcaption><strong>${n}. ${title}</strong><span>${desc}</span></figcaption><div class="dash-shell ${dark?'dark':''}" role="img" aria-label="${title} dashboard mockup with KPIs, trend information and decision-focused detail"><div class="dash-top"><b>${title}</b><small>Illustrative view</small></div><div class="dash-kpis">${metrics.join('')}</div><div class="mock-detail">${detail}</div></div></figure>`;

const gallery=[
  mock(1,'executive','Executive / board','Portfolio health, strategic KPIs, exceptions and decisions.',[
    metric('Revenue','R482m','+7.4%'),metric('EBITDA','R91m','18.9%'),metric('On plan','86%','12 / 14'),metric('Critical risks','3','Decision needed','warn')
  ],`<div class="dash-panel"><b>Portfolio performance</b>${bars([34,43,39,58,63,72,68,82])}</div><div class="dash-panel"><b>Decision queue</b><p><span class="dot bad"></span>Approve scope change</p><p><span class="dot watch"></span>Resolve supplier delay</p><p><span class="dot good"></span>Recovery on track</p></div>`),
  mock(2,'operations','Operations / command centre','Live state, alerts, throughput, exceptions and response.',[
    metric('Fleet online','97.8%','Live'),metric('Active alarms','6','2 priority'),metric('Output','412 MW','Now'),metric('Incidents','4','Open')
  ],`<div class="dash-panel"><b>Availability · 24h</b>${bars([72,78,66,82,88,74,91,84,94,89],'ops')}</div><div class="dash-panel"><b>Priority alarms</b><p><span class="dot bad"></span>WTG-17 vibration · 2m</p><p><span class="dot watch"></span>Substation comms · 8m</p><p><span class="dot watch"></span>Hydro level variance · 14m</p></div>`,true),
  mock(3,'performance','Performance / KPI','Targets, actuals, trends, variance and drill-down.',[
    metric('Production','94.6%','Target 96%','warn'),metric('Availability','98.2%','+0.4 pp'),metric('Response','18m','3m better'),metric('Quality','97.1%','On target')
  ],`<div class="dash-panel"><b>Target vs actual</b><div class="target-list"><p><span>North</span><i style="width:78%"></i><em>92%</em></p><p><span>West</span><i style="width:86%"></i><em>95%</em></p><p><span>South</span><i style="width:94%"></i><em>99%</em></p></div></div><div class="dash-panel"><b>Largest variance</b><strong class="big-risk">-8.2%</strong><small>Site North · investigate</small></div>`),
  mock(4,'finance','Financial','Budget, actual, forecast, cash and cost drivers.',[
    metric('Budget','R126m','YTD'),metric('Actual','R119m','R6.6m under'),metric('Forecast','R181m','FY'),metric('Committed','R27.8m','Open POs')
  ],`<div class="dash-panel"><b>Monthly spend</b>${bars([62,70,58,77,72,82,75,88],'finance')}</div><div class="dash-panel"><b>Cost drivers</b><div class="share-list"><p><i style="width:88%"></i><span>Maintenance 38%</span></p><p><i style="width:63%"></i><span>People 27%</span></p><p><i style="width:49%"></i><span>Services 21%</span></p></div></div>`),
  mock(5,'project','Project / portfolio','Milestones, schedule, budget, dependencies and risks.',[
    metric('On schedule','11','of 14'),metric('Budget variance','-1.8%','Favourable'),metric('Late milestones','4','2 critical','warn'),metric('Open risks','8','3 high','warn')
  ],`<div class="dash-panel"><b>Milestone runway</b><div class="timeline-mini"><p><i class="good"></i>Design freeze <small>18 Aug</small></p><p><i class="good"></i>Factory acceptance <small>29 Aug</small></p><p><i class="bad"></i>Grid approval <small>06 Sep</small></p></div></div><div class="dash-panel"><b>Risk matrix</b><div class="risk-mini"><i></i><i></i><i class="mid"></i><i class="high"></i><i></i><i class="mid"></i><i class="high"></i><i class="high"></i><i></i></div></div>`),
  mock(6,'sla','Service / SLA','Demand, backlog, ageing, SLA attainment and exceptions.',[
    metric('Received','428','+6% WoW'),metric('Resolved','451','Backlog down'),metric('Within SLA','93.7%','Target 95%','warn'),metric('Overdue','17','5 critical','warn')
  ],`<div class="dash-panel"><b>Backlog ageing</b><div class="target-list"><p><span>0–1d</span><i style="width:82%"></i><em>84</em></p><p><span>2–3d</span><i style="width:56%"></i><em>57</em></p><p><span>8d+</span><i class="danger" style="width:17%"></i><em>17</em></p></div></div><div class="dash-panel"><b>SLA by queue</b><p>Finance <strong>88%</strong></p><p>Procurement <strong>91%</strong></p><p>Facilities <strong>98%</strong></p></div>`),
  mock(7,'agent','AI / agent operations','Runs, cost, success, approvals, failures and quality.',[
    metric('Runs','1,842','24h'),metric('Success','96.4%','+1.1 pp'),metric('AI cost','R1,286','24h'),metric('Approvals','74','Human review')
  ],`<div class="dash-panel"><b>Run volume</b>${bars([35,52,44,68,73,58,84,72,91,79],'agent')}</div><div class="dash-panel"><b>Failure reasons</b><p>Source missing <strong>24</strong></p><p>Tool timeout <strong>18</strong></p><p>Validation failed <strong>11</strong></p></div>`,true),
  mock(8,'personal','Personal productivity','Priorities, time, tasks, goals and recent activity.',[
    metric('Focus','12.5h','of 15h'),metric('Tasks done','20','of 28'),metric('Meetings','4','Today'),metric('Waiting','3','Needs follow-up','warn')
  ],`<div class="dash-panel"><b>Top priorities</b><p>1 · Finish board pack</p><p>2 · Review automation pilot</p><p>3 · Plan next week</p></div><div class="dash-panel"><b>Weekly focus</b>${bars([45,62,76,58,84],'personal')}</div>`)
].join('');

const article={
  slug:'create-professional-dashboards-with-ai',
  title:'Create professional dashboards with AI: from requirements to polished decision tools',
  excerpt:'A visual, practical guide to executive, operational, KPI, financial, project, SLA, agent-operations and mobile dashboards—plus an AI-assisted workflow for designing them well.',
  type:'Visual workflow guide',category:'workflows',level:'Beginner',readTime:28,date:'2026-08-13',updated:'13 August 2026',verified:'2026-08-13',featured:true,source:'AI Compass',
  tags:['dashboards','data visualization','Power BI','analytics','design','KPIs','reporting','AI workflow','mobile'],
  sections:[
    {title:'Start with the decision, not the chart',id:'decision-first',html:`<figure class="dashboard-guide-hero"><img src="assets/dashboard-guide-hero.svg" alt="Professional analytics dashboard mockup with KPI cards, trend charts, status indicators and a decision panel"><figcaption>AI Compass original publication artwork · fictional data</figcaption></figure><p>A professional dashboard is a decision interface, not a collage of charts. Before opening Power BI, Tableau, Excel, Figma or an AI assistant, write down who will use the dashboard, what decisions they need to make, how often they will look at it and what action should follow when something is off track.</p><div class="dashboard-principle"><strong>The one-sentence test</strong><p>“This dashboard helps <em>audience</em> decide <em>what</em> by showing <em>which signals</em> at <em>what frequency</em>.”</p></div><div class="dashboard-question-grid"><div><span>01</span><strong>Audience</strong><p>Executive, manager, analyst, operator, customer or individual?</p></div><div><span>02</span><strong>Decision</strong><p>What should they know, compare, investigate or act on?</p></div><div><span>03</span><strong>Cadence</strong><p>Live, daily, weekly, monthly, quarterly or on demand?</p></div><div><span>04</span><strong>Action</strong><p>What happens when a metric is red, late or outside tolerance?</p></div></div>`},
    {title:'The eight dashboard types worth knowing',id:'types',html:`<p>Dashboard types overlap, but each has a different information hierarchy. These examples use fictional data and are AI Compass original mockups; they are design references, not screenshots of a specific product.</p><div class="dashboard-gallery">${gallery}</div>`},
    {title:'Mobile is a different composition, not a shrunken desktop',id:'mobile',html:`<p>Microsoft and Tableau both provide device-specific or mobile-optimized layouts because squeezing a wide dashboard into a phone produces tiny labels, awkward scrolling and weak hierarchy. On mobile, show the decision-critical information first and move detail behind drill-downs.</p><div class="mobile-comparison"><div class="mobile-bad"><span class="mock-label">Avoid</span><div class="phone-frame"><div class="tiny-desktop"><i></i><i></i><i></i><i></i><b></b><b></b><b></b><b></b></div></div><strong>Shrunk desktop</strong><p>Everything survives, so nothing is readable.</p></div><div class="mobile-good"><span class="mock-label">Prefer</span><div class="phone-frame"><div class="phone-dashboard"><small>Operations</small><b>97.8%</b><em>Fleet online</em><div class="phone-alert">2 priority alerts</div>${bars([35,55,47,72,64,83])}<button type="button" tabindex="-1">View exceptions</button></div></div><strong>Mobile composition</strong><p>One primary KPI, exceptions and the next action.</p></div></div>`},
    {title:'Choose the chart from the question',id:'chart-choice',html:`<p>Chart choice should follow the analytical question. Tableau describes common visual tasks such as change over time, comparison, deviation, distribution, ranking, part-to-whole, spatial patterns and flow. Use the simplest visual that makes the comparison obvious.</p><div class="table-wrap"><table><thead><tr><th>Question</th><th>Good default</th><th>Use carefully</th></tr></thead><tbody><tr><td>Change over time?</td><td>Line or column</td><td>Area when overlap obscures values</td></tr><tr><td>Compare categories?</td><td>Sorted horizontal bar</td><td>Pie/donut with many categories</td></tr><tr><td>Above or below target?</td><td>Bullet, variance bar, KPI + context</td><td>Multiple gauges</td></tr><tr><td>Distribution?</td><td>Histogram or box plot</td><td>Average alone</td></tr><tr><td>Relationship?</td><td>Scatter plot</td><td>Unrelated dual axes</td></tr><tr><td>Contribution to total?</td><td>Stacked bar or waterfall</td><td>Complex pies</td></tr><tr><td>What needs attention?</td><td>Exception list or ranked variance</td><td>Decorative KPI cards</td></tr></tbody></table></div><div class="callout"><strong>Useful rule:</strong> if a table lets the user find the exact exception faster than a chart, use the table.</div>`},
    {title:'Bad → better → excellent dashboard design',id:'quality-ladder',html:`<div class="quality-ladder"><figure class="quality bad"><figcaption><span>Bad</span><strong>Everything is important</strong></figcaption><div class="quality-canvas"><div class="rainbow-kpis"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="noisy-grid"><b></b><b></b><b></b><b></b><b></b><b></b></div></div><p>Too many colours, equal visual weight and no decision path.</p></figure><figure class="quality better"><figcaption><span>Better</span><strong>Clear hierarchy</strong></figcaption><div class="quality-canvas"><div class="clean-kpis"><i></i><i></i><i></i></div><div class="clean-grid"><b></b><b></b></div></div><p>Fewer KPIs, neutral palette and a dominant trend view.</p></figure><figure class="quality excellent"><figcaption><span>Excellent</span><strong>Decision + exception</strong></figcaption><div class="quality-canvas"><div class="decision-strip"><i></i><i></i><i class="attention"></i></div><div class="excellent-grid"><b></b><aside><i></i><i></i><i></i></aside></div></div><p>Context, exception-based colour, next action and detail on demand.</p></figure></div><div class="dashboard-principle"><strong>Professional does not mean decorative.</strong><p>White space, alignment, consistent scales, restrained colour and meaningful context usually look more premium than 3D charts, giant cards or ornamental effects.</p></div>`},
    {title:'Use AI as a design partner in six passes',id:'ai-workflow',html:`<p>AI is most useful when it helps you move through the design process deliberately. Do not ask “make me a dashboard” and accept the first page.</p><ol class="steps"><li><strong>Requirements.</strong> Convert stakeholder notes into decisions, KPIs, dimensions, filters and open questions.</li><li><strong>Metric contract.</strong> Define formula, unit, grain, source, owner, target and refresh frequency.</li><li><strong>Information architecture.</strong> Design the one-screen hierarchy before styling.</li><li><strong>Wireframe.</strong> Generate two or three options and critique them against audience and device.</li><li><strong>Implementation.</strong> Build in an approved BI or application platform; use AI to assist with formulas, queries, DAX, code or report-page drafts.</li><li><strong>Review.</strong> Verify every metric, interaction, accessibility requirement and responsive layout.</li></ol><div class="prompt-stack"><div><strong>Prompt 1 — requirements</strong><pre><code>You are helping design a decision dashboard.\nAudience: [role]\nDecision cadence: [daily / weekly / monthly]\nBusiness decisions: [list]\nAvailable data: [tables / fields / sources]\nConstraints: [screen, mobile, security, refresh]\n\nReturn the 5–8 questions the dashboard must answer, proposed KPIs with definitions, diagnostic dimensions, exceptions, missing data, and what should NOT be on the first screen.</code></pre></div><div><strong>Prompt 2 — visual architecture</strong><pre><code>Using the approved KPI definitions, design three dashboard wireframes. For each, specify reading order, chart type and why, target/variance context, drill-down, mobile differences and accessibility risks. Do not invent data or KPIs.</code></pre></div><div><strong>Prompt 3 — quality review</strong><pre><code>Review this dashboard as a skeptical executive and data-visualization reviewer. Check decision usefulness, metric clarity, hierarchy, chart choice, scales, colour semantics, accessibility, mobile layout, clutter and misleading comparisons. Rank issues by severity.</code></pre></div></div>`},
    {title:'Give every KPI a contract',id:'kpi-contract',html:`<p>A polished visual cannot rescue an ambiguous metric. Define each KPI before AI generates formulas or charts.</p><div class="table-wrap"><table><thead><tr><th>Field</th><th>Example</th></tr></thead><tbody><tr><td>Name</td><td>Portfolio availability</td></tr><tr><td>Definition</td><td>Available operating time ÷ scheduled operating time</td></tr><tr><td>Unit / grain</td><td>% · asset-day → portfolio-month</td></tr><tr><td>Direction / target</td><td>Higher is better · ≥ 98%</td></tr><tr><td>Source / owner</td><td>Approved operations model · Asset Performance</td></tr><tr><td>Refresh</td><td>Daily 06:00</td></tr><tr><td>Exception</td><td>Below 96% requires root-cause review</td></tr></tbody></table></div><p>For financial or operational dashboards, reconcile totals back to approved control totals before release. Review AI-generated formulas independently.</p>`},
    {title:'Design rules that make dashboards feel professional',id:'design-rules',html:`<div class="dashboard-rule-list"><div><span>01</span><strong>One screen, one story</strong><p>Highest-level state first; detail behind drill-down.</p></div><div><span>02</span><strong>Use colour for meaning</strong><p>Keep the interface neutral; reserve strong colour for status and exception.</p></div><div><span>03</span><strong>Show context</strong><p>A KPI needs a target, prior period, benchmark or trend.</p></div><div><span>04</span><strong>Align to a grid</strong><p>Use consistent gutters, card heights, typography and chart margins.</p></div><div><span>05</span><strong>Limit precision</strong><p>Use only the precision the decision needs.</p></div><div><span>06</span><strong>Make filters obvious</strong><p>Show active period and scope.</p></div><div><span>07</span><strong>Progressive disclosure</strong><p>Overview first, diagnostics second, transaction detail last.</p></div><div><span>08</span><strong>Accessibility</strong><p>Use contrast, labels, keyboard-friendly interactions and more than colour alone.</p></div></div><p>WCAG 2.2 specifies a minimum 4.5:1 contrast ratio for normal text at Level AA, with exceptions for large text. Microsoft’s Power BI guidance also recommends 4.5:1 for report text and avoiding colour as the only status signal.</p>`},
    {title:'A practical toolchain',id:'toolchain',html:`<p>You do not need one product for every stage. A general AI assistant can help with requirements and critique; a design or coding tool can help with mockups; and the organization’s governed BI or application platform should own production data and controls.</p><div class="table-wrap"><table><thead><tr><th>Stage</th><th>AI can help</th><th>Human responsibility</th></tr></thead><tbody><tr><td>Discovery</td><td>Summarize interviews, identify missing definitions</td><td>Confirm decisions and owners</td></tr><tr><td>Data design</td><td>Suggest measures, SQL/DAX drafts</td><td>Verify semantics and calculations</td></tr><tr><td>Wireframe</td><td>Generate layouts and alternatives</td><td>Select for audience and device</td></tr><tr><td>Build</td><td>Assist with report pages, code and formulas</td><td>Use approved sources and controls</td></tr><tr><td>QA</td><td>Critique clutter and edge cases</td><td>Reconcile numbers and sign off</td></tr></tbody></table></div><div class="callout"><strong>Power BI example:</strong> Microsoft documents that Copilot can suggest report content and create or edit report pages from natural-language prompts when the required configuration is available. Treat generated pages as a starting point and verify the semantic model, measures and visual choices.</div>`},
    {title:'Release checklist',id:'release-checklist',html:`<div class="checklist"><strong>Before publishing:</strong><ul><li>Audience and decision are explicit.</li><li>Every KPI has definition, owner, source, unit, target and refresh cadence.</li><li>Totals reconcile to an approved source.</li><li>The first screen contains only decision-critical information.</li><li>Charts match the analytical question and use consistent scales.</li><li>Colour has stable meaning and is not the only status signal.</li><li>Filters and reporting period are visible.</li><li>Desktop and mobile are reviewed separately.</li><li>Contrast, labels, keyboard use and alt text are checked where supported.</li><li>Empty, loading, stale-data and error states are designed.</li><li>A representative user can answer the intended questions without coaching.</li><li>There is an owner for maintenance and metric changes.</li></ul></div><p>The goal is not a dashboard that looks impressive in a screenshot. It is a trustworthy interface that helps someone notice the right thing and take the right next action.</p>`}
  ],
  sources:[
    {title:'Microsoft — Tips for designing a great Power BI dashboard',url:'https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards-design-tips',publisher:'Microsoft'},
    {title:'Microsoft — Design Power BI reports for accessibility',url:'https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-creating-reports',publisher:'Microsoft'},
    {title:'Microsoft — Mobile layout view in Power BI',url:'https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-create-mobile-optimized-report-mobile-layout-view',publisher:'Microsoft'},
    {title:'Microsoft — Copilot in Power BI integration overview',url:'https://learn.microsoft.com/en-us/power-bi/create-reports/copilot-integration',publisher:'Microsoft'},
    {title:'Tableau — Best practices for effective dashboards',url:'https://help.tableau.com/current/pro/desktop/en-us/dashboards_best_practices.htm',publisher:'Tableau'},
    {title:'Tableau — Choose the right chart type for your data',url:'https://help.tableau.com/current/pro/desktop/en-us/what_chart_example.htm',publisher:'Tableau'},
    {title:'W3C — Web Content Accessibility Guidelines (WCAG) 2.2',url:'https://www.w3.org/TR/WCAG22/',publisher:'W3C'},
    {title:'OpenAI — Prompt engineering best practices for ChatGPT',url:'https://help.openai.com/en/articles/10032626-prompt-engineering-best-practices',publisher:'OpenAI'}
  ]
};
if(!D.articles.some(item=>item.slug===article.slug))D.articles.unshift(article);
})();
