(()=>{
'use strict';
const D=window.AI_COMPASS_DATA;
if(!D||!Array.isArray(D.articles))return;

const slug='create-professional-dashboards-with-ai';
if(D.articles.some(item=>item.slug===slug))return;

const article={
  slug,
  title:'Create professional dashboards with AI: from requirements to polished design',
  excerpt:'A visual, practical guide to choosing the right dashboard type, designing decision-ready layouts, using AI to accelerate the work and validating the result before it goes live.',
  type:'Flagship workflow guide',
  category:'workflows',
  level:'Intermediate',
  readTime:28,
  date:'2026-08-13',
  updated:'2026-08-13',
  verified:'2026-08-13',
  featured:true,
  source:'AI Compass',
  tags:['dashboards','data visualization','Power BI','design','analytics','AI workflow','Figma','executive reporting','operations'],
  sections:[
    {
      id:'decision-first',
      title:'Start with the decision, not the chart',
      html:`<p>A professional dashboard is not a collection of attractive charts. It is a decision interface. Before you ask AI to design anything, write down who will use it, what decisions they need to make, how often they will look at it and what action should follow when something is off track.</p>
      <div class="dashboard-callout"><strong>The one-sentence test</strong><p>“This dashboard helps <em>audience</em> decide <em>decision</em> by showing <em>evidence</em> at <em>frequency</em>.” If that sentence is vague, the dashboard will usually be vague too.</p></div>
      <div class="dashboard-framework">
        <div><span>01</span><strong>Audience</strong><p>Executive, operator, analyst, project manager, finance team or customer?</p></div>
        <div><span>02</span><strong>Decision</strong><p>What should they decide, prioritise, investigate or escalate?</p></div>
        <div><span>03</span><strong>Evidence</strong><p>Which KPIs, trends, exceptions and comparisons support that decision?</p></div>
        <div><span>04</span><strong>Action</strong><p>Where does the user drill down, assign work or open the source record?</p></div>
      </div>`
    },
    {
      id:'dashboard-types',
      title:'Choose the dashboard type before you choose the visuals',
      html:`<p>Different dashboards serve different rhythms of work. An executive overview should not look like a control-room screen, and an operational screen should not be reduced to four oversized board-level KPIs.</p>
      <div class="dashboard-type-grid">
        <article><span class="dashboard-type-label">Executive</span><h3>Board / executive overview</h3><p>Few KPIs, strategic trend, portfolio health, top exceptions and decisions required. Designed for scanning in minutes.</p><small>Best cadence: weekly, monthly, quarterly</small></article>
        <article><span class="dashboard-type-label">Operational</span><h3>Command centre / live operations</h3><p>Current state, alarms, queue, availability, incidents and rapid drill-down. Designed for continuous monitoring.</p><small>Best cadence: live to daily</small></article>
        <article><span class="dashboard-type-label">Performance</span><h3>KPI / performance dashboard</h3><p>Actual vs target, trend, variance, ranking and root-cause paths. Designed for management routines.</p><small>Best cadence: daily to monthly</small></article>
        <article><span class="dashboard-type-label">Financial</span><h3>Finance / budget dashboard</h3><p>Budget vs actual, forecast, cost drivers, cash or margin, variance explanations and confidence.</p><small>Best cadence: weekly to monthly</small></article>
        <article><span class="dashboard-type-label">Delivery</span><h3>Project / portfolio dashboard</h3><p>Milestones, schedule, budget, risks, dependencies, stage gates and decisions required.</p><small>Best cadence: weekly</small></article>
        <article><span class="dashboard-type-label">Service</span><h3>SLA / service dashboard</h3><p>Volume, backlog, ageing, SLA attainment, breached items and bottlenecks.</p><small>Best cadence: live to weekly</small></article>
        <article><span class="dashboard-type-label">AI systems</span><h3>Agent / automation operations</h3><p>Runs, success rate, cost, latency, exceptions, human approvals and failure reasons.</p><small>Best cadence: live to weekly</small></article>
        <article><span class="dashboard-type-label">Personal</span><h3>Personal productivity dashboard</h3><p>Priorities, schedule, tasks, progress and recent activity. Designed around next actions rather than reporting theatre.</p><small>Best cadence: daily</small></article>
      </div>`
    },
    {
      id:'visual-examples',
      title:'Six professional dashboard mockups',
      html:`<p>These examples are intentionally different. The point is not to copy a colour scheme; it is to see how the information architecture changes with the job.</p>
      <div class="dashboard-gallery">
        <figure class="dashboard-example"><figcaption><strong>1. Executive portfolio dashboard</strong><span>Strategic scan · exceptions first</span></figcaption><div class="dash-shell dash-executive"><div class="dash-top"><div><b>Portfolio Performance</b><small>August 2026 · 18 assets</small></div><span class="dash-pill">Board view</span></div><div class="dash-kpis"><div><small>Revenue YTD</small><strong>R1.84bn</strong><em>+4.2% vs plan</em></div><div><small>Availability</small><strong>97.8%</strong><em>0.6pp below target</em></div><div><small>EBITDA margin</small><strong>42.1%</strong><em>+1.3pp YoY</em></div><div><small>Critical actions</small><strong>4</strong><em class="dash-risk">2 overdue</em></div></div><div class="dash-main-grid"><div class="dash-panel"><div class="dash-panel-title"><b>Portfolio trend</b><span>Actual · Plan</span></div><div class="mini-line-chart"><i style="--x:8%;--y:62%"></i><i style="--x:25%;--y:50%"></i><i style="--x:42%;--y:54%"></i><i style="--x:60%;--y:37%"></i><i style="--x:78%;--y:30%"></i><i style="--x:94%;--y:20%"></i></div></div><div class="dash-panel"><div class="dash-panel-title"><b>Portfolio health</b><span>18 assets</span></div><div class="health-list"><span><i class="good"></i>On plan <b>11</b></span><span><i class="warn"></i>Watch <b>5</b></span><span><i class="bad"></i>Intervene <b>2</b></span></div></div></div><div class="dash-exceptions"><b>Decisions required</b><span>Project A · approve recovery plan</span><span>Project D · capex variance +8.4%</span><span>Region West · availability below threshold</span></div></div></figure>
        <figure class="dashboard-example"><figcaption><strong>2. Operations command-centre dashboard</strong><span>Live state · alerts · action queue</span></figcaption><div class="dash-shell dash-operations"><div class="dash-top dark"><div><b>Operations Command Centre</b><small>Last refresh 14:32:08</small></div><span class="dash-live"><i></i> LIVE</span></div><div class="ops-status-row"><div><small>Fleet online</small><strong>47 / 49</strong></div><div><small>Active alarms</small><strong>12</strong></div><div><small>Priority incidents</small><strong>3</strong></div><div><small>Open work orders</small><strong>28</strong></div></div><div class="ops-grid"><div class="dash-panel map-panel"><div class="map-dots"><i class="good" style="left:18%;top:32%"></i><i class="good" style="left:39%;top:55%"></i><i class="bad" style="left:61%;top:30%"></i><i class="warn" style="left:76%;top:64%"></i><i class="good" style="left:52%;top:72%"></i></div><span>Asset status map</span></div><div class="dash-panel alert-panel"><b>Priority queue</b><p><span class="severity bad">P1</span>Turbine cluster offline <small>8 min</small></p><p><span class="severity warn">P2</span>Comms degradation <small>17 min</small></p><p><span class="severity warn">P2</span>Output variance <small>23 min</small></p></div></div><div class="spark-row"><span><small>Generation</small><b>382 MW</b><i></i></span><span><small>Availability</small><b>96.8%</b><i></i></span><span><small>Alarm rate</small><b>4.1/hr</b><i></i></span></div></div></figure>
        <figure class="dashboard-example"><figcaption><strong>3. Financial management dashboard</strong><span>Variance · forecast · drivers</span></figcaption><div class="dash-shell dash-finance"><div class="dash-top"><div><b>Finance Performance</b><small>FY2026 · Actual through Jul</small></div><span class="dash-pill">Management view</span></div><div class="dash-kpis compact"><div><small>Revenue</small><strong>R624m</strong><em>+2.8% plan</em></div><div><small>Opex</small><strong>R181m</strong><em class="dash-risk">+5.6% plan</em></div><div><small>EBITDA</small><strong>R263m</strong><em>-1.4% plan</em></div></div><div class="finance-grid"><div class="dash-panel"><b>Budget vs actual</b><div class="bar-chart"><span style="--h:72%"></span><span style="--h:64%"></span><span style="--h:82%"></span><span style="--h:77%"></span><span style="--h:90%"></span><span style="--h:86%"></span></div></div><div class="dash-panel"><b>Variance drivers</b><div class="variance-list"><span>Maintenance <b class="neg">+R8.4m</b></span><span>Energy sales <b class="pos">-R6.1m</b></span><span>Insurance <b class="neg">+R2.7m</b></span><span>FX <b class="pos">-R1.9m</b></span></div></div></div></div></figure>
        <figure class="dashboard-example"><figcaption><strong>4. Project portfolio dashboard</strong><span>Milestones · risk · schedule</span></figcaption><div class="dash-shell dash-project"><div class="dash-top"><div><b>Delivery Portfolio</b><small>12 active projects · 38 milestones</small></div><span class="dash-pill">PMO</span></div><div class="project-summary"><span><i class="good"></i>6 on track</span><span><i class="warn"></i>4 at risk</span><span><i class="bad"></i>2 delayed</span></div><div class="dash-panel project-table"><div class="table-head"><span>Project</span><span>Stage</span><span>Schedule</span><span>Budget</span><span>Next gate</span></div><div><span><b>Orion</b></span><span>Build</span><span class="status-good">On track</span><span>+1.2%</span><span>19 Aug</span></div><div><span><b>Atlas</b></span><span>Design</span><span class="status-warn">At risk</span><span>+4.8%</span><span>22 Aug</span></div><div><span><b>Nova</b></span><span>Build</span><span class="status-bad">Delayed</span><span>+7.1%</span><span>28 Aug</span></div><div><span><b>Helios</b></span><span>Close</span><span class="status-good">On track</span><span>-0.6%</span><span>31 Aug</span></div></div></div></figure>
        <figure class="dashboard-example"><figcaption><strong>5. SLA / service dashboard</strong><span>Backlog · ageing · breaches</span></figcaption><div class="dash-shell dash-service"><div class="dash-top"><div><b>Service Operations</b><small>Week 33 · All channels</small></div><span class="dash-pill">Service manager</span></div><div class="dash-kpis compact"><div><small>SLA attainment</small><strong>94.6%</strong><em class="dash-risk">Target 97%</em></div><div><small>Open backlog</small><strong>184</strong><em>↓ 12% WoW</em></div><div><small>Breached</small><strong>23</strong><em class="dash-risk">8 critical</em></div></div><div class="service-grid"><div class="dash-panel"><b>Backlog ageing</b><div class="horizontal-bars"><span><i style="width:82%"></i><em>0–1 day · 96</em></span><span><i style="width:48%"></i><em>2–3 days · 53</em></span><span><i style="width:24%"></i><em>4–7 days · 24</em></span><span><i style="width:11%"></i><em>8+ days · 11</em></span></div></div><div class="dash-panel"><b>Breach reasons</b><div class="reason-list"><span>Waiting customer <b>41%</b></span><span>Approval delay <b>29%</b></span><span>Capacity <b>18%</b></span><span>Other <b>12%</b></span></div></div></div></div></figure>
        <figure class="dashboard-example"><figcaption><strong>6. AI agent operations dashboard</strong><span>Quality · cost · human oversight</span></figcaption><div class="dash-shell dash-agent"><div class="dash-top"><div><b>Agent Operations</b><small>24h window · production</small></div><span class="dash-live"><i></i> HEALTHY</span></div><div class="dash-kpis compact"><div><small>Runs</small><strong>3,842</strong><em>+14% DoD</em></div><div><small>Task success</small><strong>96.2%</strong><em>Eval set 2.7</em></div><div><small>Cost / run</small><strong>$0.18</strong><em>↓ 7%</em></div><div><small>Human review</small><strong>6.4%</strong><em>246 runs</em></div></div><div class="agent-grid"><div class="dash-panel"><b>Outcomes</b><div class="stacked-bar"><i style="width:78%"></i><i style="width:15%"></i><i style="width:7%"></i></div><div class="legend"><span>Completed 78%</span><span>Escalated 15%</span><span>Failed 7%</span></div></div><div class="dash-panel"><b>Top failure causes</b><div class="variance-list"><span>Missing source <b>31%</b></span><span>Tool timeout <b>24%</b></span><span>Approval expired <b>18%</b></span></div></div></div></div></figure>
      </div>`
    },
    {
      id:'hierarchy',
      title:'Use visual hierarchy to make the answer obvious',
      html:`<p>Most weak dashboards fail because everything competes for attention. The user should be able to tell what matters before reading every label. A dependable hierarchy is: status and decision → headline KPIs → trend and comparison → exceptions → detail and drill-down.</p><div class="dashboard-anatomy"><div class="anatomy-band top"><span>1</span><strong>Context bar</strong><em>Title · period · scope · refresh · key filters</em></div><div class="anatomy-band kpi"><span>2</span><strong>Decision KPIs</strong><em>Only the measures that change what the user does</em></div><div class="anatomy-band trend"><span>3</span><strong>Trend + comparison</strong><em>Actual vs target · previous period · benchmark</em></div><div class="anatomy-band action"><span>4</span><strong>Exceptions and action</strong><em>What needs attention, why, owner and next step</em></div><div class="anatomy-band detail"><span>5</span><strong>Detail on demand</strong><em>Tables, drill-through, tooltips and source records</em></div></div><ul><li>Use size for hierarchy, not decoration.</li><li>Reserve strong colour for meaning: exception, status, selected state or one primary emphasis.</li><li>Keep filters together and predictable.</li><li>Show units, periods and target context close to the number.</li><li>Prefer whitespace and grouping over boxes around every element.</li></ul>`
    },
    {
      id:'bad-better-excellent',
      title:'Bad → better → excellent: what AI should improve',
      html:`<div class="dashboard-compare"><article class="compare-state bad"><span>BAD</span><h3>Dashboard as chart collection</h3><div class="compare-canvas"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><ul><li>Eight equal-weight visuals</li><li>Rainbow colour palette</li><li>No target or decision context</li><li>Every value labelled</li><li>No clear next action</li></ul></article><article class="compare-state better"><span>BETTER</span><h3>Dashboard with hierarchy</h3><div class="compare-canvas"><i class="hero"></i><i></i><i></i><i class="wide"></i><i class="wide"></i></div><ul><li>Headline KPIs separated</li><li>Trend and comparison grouped</li><li>Colour mostly neutral</li><li>Exceptions begin to stand out</li><li>Less visual noise</li></ul></article><article class="compare-state excellent"><span>EXCELLENT</span><h3>Decision interface</h3><div class="compare-canvas"><i class="hero"></i><i class="hero"></i><i class="wide action"></i><i class="wide"></i></div><ul><li>Decision questions drive layout</li><li>Exceptions link to action</li><li>Context and refresh are explicit</li><li>Drill-down handles detail</li><li>Mobile and accessibility designed in</li></ul></article></div>`
    },
    {
      id:'chart-choice',
      title:'Choose charts by the question they answer',
      html:`<div class="table-wrap"><table><thead><tr><th>Question</th><th>Usually start with</th><th>Avoid by default</th></tr></thead><tbody><tr><td>What is the current value?</td><td>KPI card with target / variance context</td><td>Gauge without a meaningful threshold</td></tr><tr><td>How is it changing?</td><td>Line chart or sparkline</td><td>Columns for dense time series</td></tr><tr><td>Which category is larger?</td><td>Sorted horizontal bar chart</td><td>Pie / donut with many slices</td></tr><tr><td>How far from target?</td><td>Bullet-style bar, variance bar or actual-vs-target line</td><td>Decorative speedometers</td></tr><tr><td>What contributes to the total?</td><td>Stacked bar for a few components; waterfall for change drivers</td><td>3D stacked charts</td></tr><tr><td>Where is the exception?</td><td>Ranked table, heatmap or exception list</td><td>Unsorted tables with hundreds of rows</td></tr><tr><td>Where is it happening?</td><td>Map only when geography changes the decision</td><td>Maps used simply because location fields exist</td></tr><tr><td>How are two variables related?</td><td>Scatter plot with reference lines</td><td>Dual-axis charts that imply false relationships</td></tr></tbody></table></div><p>Microsoft’s current Power BI guidance similarly recommends designing for the audience, keeping the overview uncluttered, putting important information where readers see it first and avoiding hard-to-read chart forms such as 3D charts. Use those principles regardless of the BI tool.</p>`
    },
    {
      id:'ai-workflow',
      title:'The AI-assisted dashboard workflow',
      html:`<p>The strongest use of AI is not “make me a dashboard.” Use AI as a sequence of specialised passes, with a human approving each important design decision.</p><ol class="dashboard-steps"><li><strong>Requirements pass</strong><p>Give AI the audience, decisions, KPIs, definitions, reporting cadence, data sources, device and constraints. Ask it to identify missing decisions and ambiguous metrics before designing.</p></li><li><strong>Information-architecture pass</strong><p>Ask for page structure, hierarchy, drill-down paths and the minimum visual set. Do not request styling yet.</p></li><li><strong>Wireframe pass</strong><p>Generate two or three grayscale layouts. Compare information density and scan path before picking one.</p></li><li><strong>Design-system pass</strong><p>Specify typography, spacing, semantic colours, component rules, chart behaviour and responsive breakpoints.</p></li><li><strong>Implementation pass</strong><p>Translate the approved design into Power BI, Tableau, Looker, Excel, a web application or another target tool.</p></li><li><strong>QA pass</strong><p>Ask AI to critique the result against the original decisions, data definitions, accessibility rules and responsive states. Then verify the numbers independently.</p></li></ol><div class="dashboard-callout"><strong>Important</strong><p>AI can accelerate layout, code, formulas, DAX, narrative summaries and critique. It does not remove the need to verify metric definitions, source data, filters or calculations.</p></div>`
    },
    {
      id:'prompt-pack',
      title:'Reusable prompts for dashboard work',
      html:`<h3>1. Requirements → information architecture</h3><pre><code>You are a senior BI product designer.\n\nDesign the information architecture for a dashboard used by [AUDIENCE].\nPrimary decisions: [DECISIONS].\nCadence: [LIVE / DAILY / WEEKLY / MONTHLY].\nData available: [SOURCES + FIELDS].\nCritical KPIs and definitions: [KPIs].\nDevice: [DESKTOP / WALLBOARD / MOBILE].\nConstraints: [BRAND / ACCESSIBILITY / TOOL].\n\nBefore proposing visuals:\n1. identify ambiguous metrics or missing decision context;\n2. reduce the dashboard to the minimum information needed;\n3. group content into status, trend, exception and detail;\n4. propose drill-down paths;\n5. explain why each visual earns its place.</code></pre><h3>2. Wireframe → professional visual design</h3><pre><code>Turn this approved dashboard wireframe into a restrained professional design.\n\nStyle: editorial enterprise software, high information clarity, no glowing gradients, no decorative AI motifs.\nUse neutral surfaces and semantic colour only for status, exception and selection.\nCreate a clear 3-level hierarchy.\nKeep KPI cards compact.\nUse consistent 8px spacing increments.\nDesign desktop at 1440px and a true mobile layout at 390px.\nShow refresh time, filter state, units and target context.\nReturn a component-by-component design specification.</code></pre><h3>3. Power BI / BI implementation prompt</h3><pre><code>Using this semantic model and approved dashboard specification, propose the Power BI report page.\n\nFor every visual provide:\n- business question answered;\n- visual type;\n- fields / measures;\n- filters and interactions;\n- title and subtitle;\n- target or comparison context;\n- tooltip / drill-through behaviour;\n- accessibility note.\n\nPrefer fewer visuals. Do not invent measures or field names. Flag anything the model does not contain.</code></pre><h3>4. Dashboard review prompt</h3><pre><code>Audit this dashboard as a skeptical executive user and BI QA reviewer.\n\nScore 0–2 for:\ndecision clarity, KPI context, visual hierarchy, chart choice, data density,\nexception visibility, accessibility, mobile behaviour, refresh/source clarity,\nand actionability.\n\nFor every score below 2, give one concrete redesign instruction.\nThen list any metric, filter or calculation that requires independent data verification.</code></pre>`
    },
    {
      id:'tools',
      title:'Which AI path should you use?',
      html:`<div class="dashboard-tool-grid"><article><strong>ChatGPT / Claude</strong><p>Best for requirements discovery, KPI definitions, wireframes, critique, chart choice, narrative design and converting screenshots into structured improvement notes.</p></article><article><strong>Power BI Copilot</strong><p>Best when your semantic model is already usable and you want natural-language help generating or editing report pages, summarising reports or exploring model-backed questions. Review generated visuals and field choices.</p></article><article><strong>Cursor / coding agents</strong><p>Best for custom React/Next.js dashboards, chart components, design-system implementation, responsive behaviour, tests and iteration against screenshots.</p></article><article><strong>Figma</strong><p>Best for deliberate component design, reusable layout systems, collaborative review and visual sign-off before implementation.</p></article><article><strong>Excel + AI</strong><p>Best for smaller operational dashboards where the source already lives in structured tables and the audience needs familiar distribution rather than a new platform.</p></article><article><strong>BI tool + coded companion</strong><p>Useful when governed metrics remain in Power BI or another BI platform but a custom portal handles workflow, commentary, approvals or cross-system navigation.</p></article></div><p>Microsoft’s current Power BI documentation says Copilot can suggest report content and create or edit report pages from natural-language prompts when the required tenant, capacity and semantic-model conditions are met. Treat it as an accelerator rather than an automatic design authority.</p>`
    },
    {
      id:'responsive',
      title:'Design mobile as a different composition',
      html:`<p>A mobile dashboard is not a desktop dashboard squeezed into a narrow viewport. Prioritise the top decision, reduce simultaneous comparisons and move detail behind taps or drill-through.</p><div class="mobile-dashboard-demo"><div class="phone-frame"><div class="phone-top">Portfolio <span>•••</span></div><div class="phone-kpi"><small>Availability</small><strong>97.8%</strong><em>0.6pp below target</em></div><div class="phone-alert"><b>2 critical exceptions</b><span>Open action queue →</span></div><div class="phone-chart"><b>30-day trend</b><div class="mini-line-chart"><i style="--x:8%;--y:62%"></i><i style="--x:28%;--y:48%"></i><i style="--x:49%;--y:55%"></i><i style="--x:69%;--y:32%"></i><i style="--x:91%;--y:24%"></i></div></div><div class="phone-list"><span>Asset A <b>99.1%</b></span><span>Asset B <b>98.6%</b></span><span class="risk">Asset C <b>91.4%</b></span></div></div><div class="mobile-notes"><strong>Mobile priorities</strong><ul><li>One-column flow.</li><li>Decision and exception first.</li><li>Touch-friendly filters.</li><li>No horizontal chart squeezing.</li><li>Short labels and readable values.</li><li>Detail opens separately.</li></ul></div></div>`
    },
    {
      id:'quality-check',
      title:'Release checklist: professional before pretty',
      html:`<div class="checklist"><strong>Data and meaning</strong><ul><li>Every KPI has an owner, definition, unit and reporting period.</li><li>Totals reconcile to the source system.</li><li>Filters and default states are visible and tested.</li><li>Targets, benchmarks and variance directions are correct.</li><li>Refresh time and data latency are understandable.</li></ul></div><div class="checklist"><strong>Design and usability</strong><ul><li>The main decision can be understood in under ten seconds.</li><li>No chart exists only for decoration.</li><li>Colour has a consistent semantic meaning.</li><li>Text, labels and interactive elements remain usable at realistic screen sizes.</li><li>Important information does not depend on colour alone.</li><li>Mobile is intentionally composed, not merely scaled.</li></ul></div><div class="checklist"><strong>AI-specific QA</strong><ul><li>Generated calculations, DAX, SQL and formulas are independently checked.</li><li>AI did not invent fields, targets or business definitions.</li><li>Generated summaries can be traced to displayed or governed data.</li><li>Prompts and design decisions are versioned when the dashboard is operationally important.</li></ul></div><p>WCAG 2.2 requires at least 4.5:1 contrast for normal text in the relevant AA criterion, with specific exceptions for large text. Treat accessibility as a design constraint from the first wireframe rather than a late compliance pass.</p>`
    }
  ],
  sources:[
    {title:'Microsoft Learn — Tips for designing a great Power BI dashboard',url:'https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards-design-tips',publisher:'Microsoft'},
    {title:'Microsoft Learn — Use Copilot with Power BI reports and semantic models',url:'https://learn.microsoft.com/en-us/power-bi/create-reports/copilot-reports-overview',publisher:'Microsoft'},
    {title:'Microsoft Learn — Create and edit Power BI reports with Copilot',url:'https://learn.microsoft.com/en-nz/power-bi/create-reports/copilot-create-reports',publisher:'Microsoft'},
    {title:'W3C — Web Content Accessibility Guidelines (WCAG) 2.2',url:'https://www.w3.org/TR/WCAG22/',publisher:'W3C'},
    {title:'OpenAI — Prompt engineering best practices for ChatGPT',url:'https://help.openai.com/en/articles/10032626-prompt-engineering-best-practices',publisher:'OpenAI'}
  ]
};

D.articles.unshift(article);
})();