(()=>{
'use strict';
const verified='2026-08-17';
window.AI_COMPASS_DISCOVERY={
  verified,
  tools:[
    {id:'chatgpt',name:'ChatGPT',provider:'OpenAI',bestFor:'General-purpose AI work, research, writing, analysis and multimodal tasks.',level:'Beginner',type:'Assistant',url:'https://chatgpt.com/',sourceUrl:'https://openai.com/chatgpt/overview/',watch:'Capabilities vary by plan and model; verify workspace privacy and admin controls before company use.',tags:['general','research','writing','multimodal','work']},
    {id:'claude',name:'Claude',provider:'Anthropic',bestFor:'Long-form reasoning, research, writing, coding and document-heavy work.',level:'Beginner',type:'Assistant',url:'https://claude.ai/',sourceUrl:'https://www.anthropic.com/claude',watch:'Available capabilities differ across Claude plans and enterprise configurations.',tags:['reasoning','research','writing','coding','documents']},
    {id:'gemini',name:'Gemini',provider:'Google',bestFor:'General AI assistance with strong integration into Google products and multimodal workflows.',level:'Beginner',type:'Assistant',url:'https://gemini.google.com/',sourceUrl:'https://gemini.google.com/',watch:'Product features and Workspace availability can vary by account and region.',tags:['general','google','workspace','multimodal']},
    {id:'m365-copilot',name:'Microsoft 365 Copilot',provider:'Microsoft',bestFor:'AI-assisted work inside Word, Excel, PowerPoint, Outlook, Teams and Microsoft 365.',level:'Beginner',type:'Work suite',url:'https://www.microsoft.com/microsoft-365-copilot',sourceUrl:'https://learn.microsoft.com/en-us/copilot/microsoft-365/',watch:'Value depends heavily on Microsoft 365 data quality, permissions and organisational rollout.',tags:['microsoft','office','enterprise','work']},
    {id:'notebooklm',name:'NotebookLM',provider:'Google',bestFor:'Source-grounded study, synthesis and questioning across a defined collection of material.',level:'Beginner',type:'Research',url:'https://notebooklm.google.com/',sourceUrl:'https://notebooklm.google/',watch:'Treat generated summaries as aids; verify important conclusions against the supplied sources.',tags:['research','documents','study','grounding']},
    {id:'cursor',name:'Cursor',provider:'Cursor',bestFor:'AI-assisted software development inside an editor with repository context.',level:'Intermediate',type:'Coding',url:'https://www.cursor.com/',sourceUrl:'https://docs.cursor.com/',watch:'Repository-wide actions still require review, tests, security checks and source-control discipline.',tags:['coding','developer','ide','agents']}
  ],
  models:[
    {id:'openai-gpt',name:'GPT family',provider:'OpenAI',access:'Hosted/API',bestFor:'General reasoning, coding, tool use and multimodal application development.',openness:'Closed weights',url:'https://platform.openai.com/docs/models',watch:'Choose a model by task, latency, quality and cost rather than assuming the largest model is always best.',tags:['reasoning','coding','tools','multimodal']},
    {id:'anthropic-claude',name:'Claude family',provider:'Anthropic',access:'Hosted/API',bestFor:'Reasoning, coding, long-form work and agentic applications.',openness:'Closed weights',url:'https://docs.anthropic.com/en/docs/about-claude/models/overview',watch:'Model availability and capabilities change; use the provider model documentation as the current source.',tags:['reasoning','coding','agents','documents']},
    {id:'google-gemini',name:'Gemini family',provider:'Google',access:'Hosted/API',bestFor:'Multimodal applications, reasoning and Google ecosystem development.',openness:'Closed weights',url:'https://ai.google.dev/gemini-api/docs/models',watch:'API and product surfaces can expose different model options and limits.',tags:['multimodal','reasoning','google','developer']},
    {id:'meta-llama',name:'Llama family',provider:'Meta',access:'Open-weight ecosystem',bestFor:'Custom deployment, research and applications that need more control over model hosting.',openness:'Open weights; licence-specific',url:'https://www.llama.com/',watch:'Open weights do not automatically mean open source; inspect the exact licence and deployment obligations.',tags:['open-weight','local','self-hosted','research']},
    {id:'mistral',name:'Mistral models',provider:'Mistral AI',access:'Hosted and open-weight options',bestFor:'European-hosted options, application development and selected self-hosted use cases.',openness:'Mixed by model',url:'https://docs.mistral.ai/getting-started/models/models_overview/',watch:'Licensing and availability differ between models; verify the exact model rather than the family name.',tags:['open-weight','api','enterprise','europe']},
    {id:'qwen',name:'Qwen family',provider:'Alibaba Cloud / Qwen',access:'Hosted and open-weight ecosystem',bestFor:'Research, multilingual work and self-hosted experimentation where the selected licence fits.',openness:'Mixed by model',url:'https://qwenlm.github.io/',watch:'Check the exact repository, licence, model card and serving requirements before production use.',tags:['open-weight','multilingual','local','research']}
  ],
  courses:[
    {id:'openai-ai-foundations',title:'AI Foundations',provider:'OpenAI Academy',level:'Beginner',audience:'People new to AI or wanting stronger workplace fundamentals.',duration:'~70 minutes',cost:'Free',certificate:'Course completion certificate',url:'https://academy.openai.com/public/courses/ai-foundations-juzjs?autoEnroll=true',sourceUrl:'https://academy.openai.com/pages/courses',rating:9.3,why:'A concise hands-on introduction that teaches prompting, context, review and responsible workplace use around a real task.',value:'Strong first course for non-technical staff because it moves quickly from concepts into practical habits.',skip:'Skip if you already use AI confidently every day and want technical implementation depth.',path:'start-here',verified},
    {id:'openai-applied-foundations',title:'Applied AI Foundations',provider:'OpenAI Academy',level:'Intermediate',audience:'Active AI users who want repeatable workflows instead of isolated chats.',duration:'Self-paced',cost:'Free',certificate:'Course completion certificate',url:'https://academy.openai.com/pages/courses',sourceUrl:'https://academy.openai.com/pages/courses',rating:9.2,why:'Focuses on breaking recurring work into steps, identifying where AI helps and adding review points.',value:'Useful bridge from “prompting” to workflow thinking for knowledge workers and team champions.',skip:'Skip if your priority is API development, model training or deep software engineering.',path:'work-smarter',verified},
    {id:'openai-agents-workflows',title:'Agents and Workflows',provider:'OpenAI Academy',level:'Intermediate',audience:'Comfortable AI users beginning to direct agents and structured workflows.',duration:'Self-paced',cost:'Free',certificate:'Course completion certificate',url:'https://academy.openai.com/pages/courses',sourceUrl:'https://academy.openai.com/pages/courses',rating:9.1,why:'Teaches structured work, context, boundaries, output definition and human review rather than treating agents as magic automation.',value:'Strong conceptual preparation before building or approving workplace agents.',skip:'Developers needing production orchestration code should pair it with technical SDK documentation and AI Compass builder guides.',path:'build-ai-systems-at-work',verified},
    {id:'anthropic-ai-fluency',title:'AI Fluency: Frameworks and Foundations',provider:'Anthropic',level:'Beginner',audience:'Anyone who wants transferable skills for collaborating with AI rather than product-specific button training.',duration:'12 lessons · 3–4 hours',cost:'Free',certificate:'Not the primary reason to take it',url:'https://www.anthropic.com/ai-fluency/overview',sourceUrl:'https://www.anthropic.com/ai-fluency/overview',rating:9.4,why:'Its 4D framework—Delegation, Description, Discernment and Diligence—gives learners a durable mental model for effective and responsible AI use.',value:'One of the strongest vendor-created courses for skills that remain useful across multiple AI tools.',skip:'Skip only if you need a short product tutorial rather than a broader AI fluency framework.',path:'start-here',verified},
    {id:'google-mlcc',title:'Machine Learning Crash Course',provider:'Google for Developers',level:'Intermediate',audience:'Developers, analysts and technical learners who want to understand machine-learning foundations beneath modern AI.',duration:'Modular · self-paced',cost:'Free',certificate:'Learning-focused',url:'https://developers.google.com/machine-learning/crash-course',sourceUrl:'https://developers.google.com/machine-learning/crash-course',rating:9.0,why:'Combines videos, interactive visualisations, quizzes and browser-based exercises across ML fundamentals, embeddings, LLMs, production ML and fairness.',value:'Excellent technical foundation for builders who use LLMs but have never learned the machine-learning concepts underneath them.',skip:'Not the best first course for a non-technical employee who mainly wants workplace productivity skills.',path:'build-agents',verified},
    {id:'microsoft-ms4014',title:'MS-4014: Build a foundation to build AI agents and extend Microsoft 365 Copilot',provider:'Microsoft Learn',level:'Beginner',audience:'Developers and app makers in Microsoft 365 environments deciding between low-code and pro-code agent approaches.',duration:'1 day',cost:'Self-paced material free; instructor-led pricing varies',certificate:'Course / Microsoft Learn achievements vary',url:'https://learn.microsoft.com/en-us/training/courses/ms-4014',sourceUrl:'https://learn.microsoft.com/en-us/training/courses/ms-4014',rating:8.9,why:'Compares Copilot Studio, Microsoft Foundry and Microsoft 365 Agents Toolkit while grounding the decision in real agent use cases.',value:'Especially useful for corporate teams already standardized on Microsoft 365 and Power Platform.',skip:'Skip if your organisation is not using the Microsoft ecosystem or you need provider-neutral agent engineering.',path:'build-ai-systems-at-work',verified}
  ],
  resources:[
    {id:'prompt-library',title:'Reusable prompt template library',type:'Template',audience:'All levels',summary:'Copyable patterns for research, transformation, planning, review and workflow prompts.',href:'#article/reusable-prompt-template-library',source:'AI Compass',tags:['prompts','templates','work']},
    {id:'research-evidence-matrix',title:'Research evidence-matrix workflow',type:'Framework',audience:'Researchers and analysts',summary:'Structure claims, source quality, dates, contradictions and confidence before synthesis.',href:'#article/build-a-professional-research-report-with-ai',source:'AI Compass',tags:['research','evidence','verification']},
    {id:'agent-pilot-charter',title:'Workplace agent pilot charter',type:'Checklist',audience:'Corporate AI teams',summary:'Define outcome, scope, data, autonomy, prohibited actions, evaluation and release evidence.',href:'#article/build-and-test-agentic-ai-at-work',source:'AI Compass',tags:['agents','pilot','governance']},
    {id:'enterprise-architecture-canvas',title:'Enterprise AI architecture canvas',type:'Framework',audience:'AI builders and architects',summary:'Map model, retrieval, tools, orchestration, identity, approvals, observability and systems of record.',href:'#article/design-enterprise-ai-architecture',source:'AI Compass',tags:['architecture','enterprise','agents']},
    {id:'rag-evaluation-checklist',title:'RAG trust and evaluation checklist',type:'Checklist',audience:'AI builders',summary:'Review permissions, retrieval quality, citations, freshness, conflicting sources and failure behavior.',href:'#article/build-trustworthy-enterprise-rag',source:'AI Compass',tags:['rag','evaluation','security']},
    {id:'agent-security-checklist',title:'Agent identity and least-privilege checklist',type:'Checklist',audience:'Security and platform teams',summary:'Review identities, scopes, delegated permissions, approvals, secrets and consequential tool access.',href:'#article/secure-enterprise-ai-agents',source:'AI Compass',tags:['security','identity','permissions']},
    {id:'eval-release-gates',title:'AI evaluation and release-gate framework',type:'Framework',audience:'AI product teams',summary:'Create golden sets, adversarial cases, graders, regression tests and evidence-based go/no-go gates.',href:'#article/build-enterprise-ai-evaluation-framework',source:'AI Compass',tags:['evaluation','testing','quality']},
    {id:'github-directory',title:'Curated AI repositories',type:'Directory',audience:'Developers and builders',summary:'Maintainer-owned projects and open-source resources with category, language and review metadata.',href:'#repos',source:'AI Compass',tags:['github','open-source','developer']}
  ]
};
})();