(()=>{
'use strict';
const MC=()=>window.AI_COMPASS_MY_COMPASS;
const C=()=>window.AI_COMPASS_COMMUNITY;
const D=()=>window.AI_COMPASS_DATA||{articles:[]};
const L=()=>window.AI_COMPASS_LIBRARY||{learningPaths:[]};
const X=()=>window.AI_COMPASS_DISCOVERY||{tools:[],models:[],courses:[],resources:[]};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fmt=value=>{try{return new Intl.DateTimeFormat('en-ZA',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value))}catch{return''}};
const route=()=>{const raw=(location.hash||'#home').slice(1).split('?')[0];const parts=raw.split('/').filter(Boolean);return{page:parts[0]||'home',arg:parts[1]||''}};
let token=0;

function identity(){return C()?.identity?.()||{user:null,profile:null,role:'guest'};}
function pathById(id){return (L().learningPaths||[]).find(p=>p.id===id);}
function guideBySlug(slug){return (D().articles||[]).find(a=>a.slug===slug);}
function contentInfo(type,id){
 if(type==='guide'){const a=guideBySlug(id);return a?{title:a.title,href:`#article/${a.slug}`,meta:`${a.level} · ${a.readTime} min`}:null;}
 if(type==='learning-path'){const p=pathById(id);return p?{title:p.title,href:`#learn/${p.id}`,meta:`${p.duration} · ${p.steps.length} lessons`}:null;}
 const map={tool:'tools',model:'models',course:'courses',resource:'resources'};const key=map[type];const collection=key?X()[key]||[]:[];const item=collection.find(v=>v.id===id);if(!item)return null;return{title:item.name||item.title,href:`#${key}`,meta:item.provider||item.type||type};
}
function progressMap(records){const map=new Map();for(const row of records||[]){if(!map.has(row.path_id))map.set(row.path_id,new Set());map.get(row.path_id).add(row.step_slug);}return map;}
function percent(done,total){return total?Math.round(done/total*100):0;}
function show(message,type='success'){let node=document.getElementById('myCompassNotice');if(!node){node=document.createElement('div');node.id='myCompassNotice';node.className='community-notice';document.body.appendChild(node);}node.className=`community-notice ${type}`;node.textContent=message;node.classList.add('show');clearTimeout(window.__mcNotice);window.__mcNotice=setTimeout(()=>node.classList.remove('show'),3000);}

function nav(){
 const utility=document.querySelector('.utility-inner div');
 if(utility&&!utility.querySelector('a[href="#my-compass"]'))utility.insertAdjacentHTML('afterbegin','<a href="#my-compass">My Compass</a>');
 const session=document.querySelector('.community-session>div');if(session&&identity().user&&!session.querySelector('a[href="#my-compass"]'))session.insertAdjacentHTML('afterbegin','<a href="#my-compass">My Compass</a>');
}
function hero(title,copy,stat='My',label='Compass'){return`<section class="page-hero my-compass-hero"><div class="container page-hero-grid"><div><p class="eyebrow">Personal AI Compass</p><h1>${esc(title)}</h1><p>${esc(copy)}</p></div><div class="page-stat"><strong>${esc(stat)}</strong><span>${esc(label)}</span></div></div></section>`;}
function signedOut(){return`${hero('Your learning and AI interests, remembered.','Create a free profile to follow useful content, like guides, track learning progress and participate in community discussions.','Free','profile')}<section class="content-section"><div class="container narrow"><div class="my-compass-signin"><p class="eyebrow">Start My Compass</p><h2>One profile across learning and community.</h2><p>AI Compass uses passwordless email sign-in. Your public profile never exposes your email address.</p><div><a class="button" href="#community/profile">Sign in / create profile</a><a href="#learn">Explore learning first →</a></div></div></div></section>`;}
function followCard(row){const info=contentInfo(row.content_type,row.content_id);if(!info)return'';return`<a class="my-follow-card" href="${esc(info.href)}"><span>${esc(row.content_type.replace('-',' '))}</span><h3>${esc(info.title)}</h3><p>${esc(info.meta)}</p><small>Following since ${esc(fmt(row.created_at))}</small></a>`;}
function pathCard(path,completed){const done=completed.size;const pct=percent(done,path.steps.length);const next=path.steps.find(slug=>!completed.has(slug));const nextGuide=next?guideBySlug(next):null;return`<article class="my-progress-card"><div class="my-progress-top"><span>${done}/${path.steps.length} lessons</span><strong>${pct}%</strong></div><h3>${esc(path.title)}</h3><div class="my-progress-bar"><span style="width:${pct}%"></span></div><p>${done===path.steps.length?'Path complete. Revisit any lesson whenever it becomes useful.':nextGuide?`Next: ${esc(nextGuide.title)}`:'Continue when you are ready.'}</p><a href="#learn/${esc(path.id)}">${done===path.steps.length?'Review path':'Continue learning'} →</a></article>`;}

async function renderMyCompass(){
 const current=++token;const main=document.getElementById('main');if(!main)return;await C().ready;await window.AI_COMPASS_CONTENT_READY;if(current!==token)return;const ident=identity();
 if(!ident.user){main.innerHTML=signedOut();document.title='My Compass — AI Compass';nav();return;}
 const state=await MC().myState();if(current!==token)return;const progress=progressMap(state.progress);const pathCards=(L().learningPaths||[]).filter(p=>progress.has(p.id)).map(p=>pathCard(p,progress.get(p.id))).join('');const followed=state.follows.map(followCard).filter(Boolean).join('');const profile=ident.profile;
 main.innerHTML=`${hero(profile?`Welcome back, ${profile.display_name}.`:'Your My Compass dashboard.','Continue learning, return to followed content and keep your community identity in one place.',state.progress.length,'completed lessons')}
 <section class="my-compass-summary"><div class="container my-summary-grid"><div><span>Learning</span><strong>${state.progress.length}</strong><small>completed lessons</small></div><div><span>Following</span><strong>${state.follows.length}</strong><small>saved interests</small></div><div><span>Likes</span><strong>${state.likes.length}</strong><small>guides/resources liked</small></div><div><span>Community</span><strong>${profile?'Ready':'1 step'}</strong><small>${profile?'profile active':'complete your profile'}</small></div></div></section>
 ${!profile?`<section class="content-section compact-section"><div class="container"><div class="community-callout"><div><strong>Finish your community profile</strong><p>Choose a public username before posting or replying.</p></div><a class="button small" href="#community/profile">Complete profile</a></div></div></section>`:''}
 <section class="content-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">Continue learning</p><h2>${pathCards?'Pick up where you left off.':'Start a learning path.'}</h2><p>Your completion state is private to your account.</p></div><a class="text-link" href="#learn">All learning paths →</a></div><div class="my-progress-grid">${pathCards||`<div class="my-empty-panel"><strong>No completed lessons yet.</strong><p>AI Essentials is a good starting point if you are unsure where to begin.</p><a href="#learn">Choose a path →</a></div>`}</div></div></section>
 <section class="content-section tinted"><div class="container"><div class="section-heading"><div><p class="eyebrow">Following</p><h2>${followed?'Content you chose to keep close.':'Follow guides and learning paths you want to revisit.'}</h2></div></div><div class="my-follow-grid">${followed||`<div class="my-empty-panel"><strong>Nothing followed yet.</strong><p>Use Follow on guide pages or learning paths to build your personal library.</p><a href="#guides">Browse guides →</a></div>`}</div></div></section>
 <section class="content-section"><div class="container"><div class="my-community-card"><div><p class="eyebrow">Community</p><h2>${profile?'Join the discussion.':'Complete your public community identity.'}</h2><p>${profile?'Ask questions, share what you built or help someone else move forward.':'Your email stays private; only the username, display name and optional bio you choose are public.'}</p></div><div>${profile?'<a class="button" href="#community">Open Community</a>':'<a class="button" href="#community/profile">Create profile</a>'}<a href="#community">Browse discussions →</a></div></div></div></section>`;
 document.title='My Compass — AI Compass';nav();
}

function guideCategory(article){const text=`${article.title||''} ${(article.tags||[]).join(' ')} ${article.category||''}`.toLowerCase();if(/agent|orchestrat/.test(text))return'agents-orchestration';if(/enterprise|govern|security|identity|rag|evaluation/.test(text))return'enterprise-ai';if(/code|api|developer/.test(text))return'coding-builders';if(/prompt|research|source|structured/.test(text))return'prompting-research';if(/workflow|automat/.test(text))return'automation-workflows';if(/office|excel|presentation|workplace/.test(text))return'ai-for-work';return'general';}
async function decorateGuide(slug){
 const current=++token;await C().ready;const article=guideBySlug(slug);if(!article||current!==token)return;const main=document.getElementById('main');if(!main||main.querySelector('.my-guide-engagement'))return;
 const [state,discussion]=await Promise.all([MC().contentState('guide',slug),MC().linkedThreads('guide',slug)]);if(current!==token||route().page!=='article'||route().arg!==slug)return;const ident=identity();const anchor=main.querySelector('.article-freshness')||main.querySelector('.article-taxonomy')||main.querySelector('.article-labels');
 const actions=document.createElement('section');actions.className='my-guide-engagement';actions.innerHTML=`<div class="container narrow"><div class="my-guide-actions"><div><span class="eyebrow">My Compass</span><strong>Was this useful?</strong></div><div><button type="button" data-mc-action="like-guide" data-id="${esc(slug)}" data-active="${state.liked?'1':'0'}" ${ident.user?'':'disabled'}>${state.liked?'Liked':'Like'} · ${state.likes}</button><button type="button" data-mc-action="follow-guide" data-id="${esc(slug)}" data-active="${state.followed?'1':'0'}" ${ident.user?'':'disabled'}>${state.followed?'Following':'Follow'}</button><a href="#guide-discussion">Discuss · ${discussion.threads.length}</a></div></div>${!ident.user?'<p class="my-guide-signin"><a href="#community/profile">Sign in free</a> to like, follow and start a discussion.</p>':''}</div>`;
 if(anchor)anchor.insertAdjacentElement('afterend',actions);else main.prepend(actions);
 const section=document.createElement('section');section.className='content-section my-guide-discussion';section.id='guide-discussion';const threadRows=discussion.threads.map(t=>{const p=discussion.profiles.get(t.author_id);return`<a href="#community/thread/${esc(t.id)}"><div><span>${esc(p?.display_name||p?.username||'Community member')}</span><h3>${esc(t.title)}</h3><p>${esc((t.body||'').slice(0,180))}${(t.body||'').length>180?'…':''}</p></div><strong>${discussion.replyCounts[t.id]||0} replies →</strong></a>`;}).join('');
 const canPost=ident.user&&ident.profile;section.innerHTML=`<div class="container narrow"><div class="section-heading"><div><p class="eyebrow">Community discussion</p><h2>Questions and implementation notes about this guide.</h2><p>Community posts are user-generated and remain separate from AI Compass editorial guidance.</p></div><a class="text-link" href="#community">Open forum →</a></div><div class="my-linked-threads">${threadRows||'<div class="my-empty-panel"><strong>No discussions yet.</strong><p>Start one with a specific question, implementation detail or useful experience.</p></div>'}</div>${canPost?`<details class="my-guide-compose"><summary>Start a discussion about this guide</summary><form id="myGuideDiscussion" data-slug="${esc(slug)}" data-category="${esc(guideCategory(article))}"><label>Discussion title<input name="title" minlength="8" maxlength="160" required placeholder="What should other readers understand or help with?"></label><label>Context<textarea name="body" minlength="20" maxlength="12000" rows="6" required placeholder="Explain what you are trying, what happened and what would make a useful answer."></textarea></label><button class="button" type="submit">Publish to Community</button></form></details>`:ident.user?'<div class="community-callout"><div><strong>Create your public username first</strong><p>Your email is never shown in the forum.</p></div><a class="button small" href="#community/profile">Complete profile</a></div>':'<div class="community-callout"><div><strong>Want to discuss this guide?</strong><p>Sign in free to start a linked community thread.</p></div><a class="button small" href="#community/profile">Sign in</a></div>'}</div>`;main.appendChild(section);
}

async function decorateLearning(pathId){
 const current=++token;await C().ready;await window.AI_COMPASS_CONTENT_READY;const path=pathById(pathId);if(!path||current!==token)return;const main=document.getElementById('main');if(!main||main.querySelector('.my-learning-progress'))return;const ident=identity();const completed=ident.user?new Set((await MC().pathProgress(pathId)).map(r=>r.step_slug)):new Set();if(current!==token)return;const state=await MC().contentState('learning-path',pathId);if(current!==token)return;const done=completed.size;const panel=document.createElement('section');panel.className='my-learning-progress';panel.innerHTML=`<div class="container narrow"><div class="my-learning-progress-inner"><div><p class="eyebrow">My Compass progress</p><h2>${ident.user?`${done} of ${path.steps.length} lessons complete`:'Track this path across visits'}</h2><div class="my-progress-bar"><span style="width:${percent(done,path.steps.length)}%"></span></div><p>${ident.user?'Completion is private to your account. Mark a lesson complete when you can apply it, not merely when you have opened it.':'Sign in free to mark lessons complete and continue on another device.'}</p></div><div>${ident.user?`<button type="button" data-mc-action="follow-path" data-id="${esc(pathId)}" data-active="${state.followed?'1':'0'}">${state.followed?'Following path':'Follow path'}</button>`:`<a class="button small" href="#community/profile">Sign in</a>`}</div></div></div>`;const hero=main.querySelector('.page-hero');hero?.insertAdjacentElement('afterend',panel);
 if(ident.user){main.querySelectorAll('.lesson').forEach((lesson,index)=>{const slug=path.steps[index];if(!slug)return;const isDone=completed.has(slug);const control=document.createElement('button');control.type='button';control.className=`my-lesson-check ${isDone?'complete':''}`;control.dataset.mcAction='lesson';control.dataset.path=pathId;control.dataset.slug=slug;control.dataset.active=isDone?'1':'0';control.innerHTML=`<span>${isDone?'✓':'○'}</span>${isDone?'Completed':'Mark complete'}`;lesson.appendChild(control);});}
}

async function refreshCurrent(){nav();const r=route();try{if(r.page==='my-compass')return await renderMyCompass();if(r.page==='article'&&r.arg)return await decorateGuide(r.arg);if(r.page==='learn'&&r.arg)return await decorateLearning(r.arg);}catch(error){console.warn('My Compass enhancement failed',error);}}

async function click(event){const el=event.target.closest('[data-mc-action]');if(!el)return;try{const action=el.dataset.mcAction;if(action==='like-guide'){await MC().toggleLike('guide',el.dataset.id,el.dataset.active==='1');show(el.dataset.active==='1'?'Like removed.':'Guide liked.');return refreshCurrent();}if(action==='follow-guide'){await MC().toggleFollow('guide',el.dataset.id,el.dataset.active==='1');show(el.dataset.active==='1'?'Guide unfollowed.':'Guide followed.');return refreshCurrent();}if(action==='follow-path'){await MC().toggleFollow('learning-path',el.dataset.id,el.dataset.active==='1');show(el.dataset.active==='1'?'Path unfollowed.':'Path followed.');return refreshCurrent();}if(action==='lesson'){const completing=el.dataset.active!=='1';await MC().setStep(el.dataset.path,el.dataset.slug,completing);show(completing?'Lesson marked complete.':'Lesson marked incomplete.');return refreshCurrent();}}catch(error){show(error.message||'My Compass action failed.','error');}}
async function submit(event){const form=event.target;if(form.id!=='myGuideDiscussion')return;event.preventDefault();try{const fd=new FormData(form);const thread=await C().createThread({category_id:form.dataset.category,title:fd.get('title'),body:fd.get('body'),linked_content_type:'guide',linked_content_id:form.dataset.slug});show('Discussion published.');location.hash=`#community/thread/${thread.id}`;}catch(error){show(error.message||'Could not publish discussion.','error');}}

document.addEventListener('click',click);document.addEventListener('submit',submit);document.addEventListener('ai-compass-community-auth',()=>setTimeout(refreshCurrent,100));document.addEventListener('DOMContentLoaded',()=>setTimeout(refreshCurrent,260));addEventListener('hashchange',()=>setTimeout(refreshCurrent,260));
})();
