import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';

const holder=document.getElementById('scene'),scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x05070b,.052);
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(.8,.25,11.5);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.35:1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;holder.appendChild(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),innerWidth<700?.58:.82,.65,.72));
const world=new THREE.Group();world.position.set(innerWidth<760?1.55:2.75,innerWidth<760?1.8:.2,0);scene.add(world);
const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.48,innerWidth<700?5:7),new THREE.MeshPhysicalMaterial({color:0x111824,metalness:.42,roughness:.16,transmission:.18,thickness:1.8,ior:1.34,clearcoat:1,clearcoatRoughness:.08,iridescence:1,iridescenceIOR:1.55,iridescenceThicknessRange:[120,420]}));core.scale.set(1,1.08,1);world.add(core);
const inner=new THREE.Mesh(new THREE.IcosahedronGeometry(1.08,5),new THREE.MeshBasicMaterial({color:0x48d9ba,transparent:true,opacity:.055,wireframe:true}));world.add(inner);
const ribbons=[],defs=[{r:2.17,t:.052,c:0xa9baff,rot:[1.05,.12,.42]},{r:2.55,t:.035,c:0x74f4d1,rot:[-.5,.95,-.2]},{r:2.93,t:.022,c:0x7e91bd,rot:[.5,-.6,1.1]}];
for(const d of defs){const curve=new THREE.CatmullRomCurve3(Array.from({length:80},(_,i)=>{const a=i/80*Math.PI*2,w=.18*Math.sin(a*3+d.r);return new THREE.Vector3(Math.cos(a)*(d.r+w),Math.sin(a)*(d.r+w),.24*Math.sin(a*2))}),true,'catmullrom',.4),m=new THREE.Mesh(new THREE.TubeGeometry(curve,innerWidth<700?120:240,d.t,7,true),new THREE.MeshStandardMaterial({color:d.c,metalness:.85,roughness:.22,emissive:d.c,emissiveIntensity:.08}));m.rotation.set(...d.rot);world.add(m);ribbons.push(m)}
const nodes=new THREE.Group();world.add(nodes);const ng=new THREE.SphereGeometry(.075,16,16),nm=new THREE.MeshPhysicalMaterial({color:0xe9f6ff,metalness:.25,roughness:.1,emissive:0x8df7d7,emissiveIntensity:1.4});for(let i=0;i<(innerWidth<700?22:34);i++){const a=Math.random()*Math.PI*2,p=Math.acos(2*Math.random()-1),r=2.1+Math.random()*1.2,m=new THREE.Mesh(ng,nm);m.position.set(r*Math.sin(p)*Math.cos(a),r*Math.cos(p),r*Math.sin(p)*Math.sin(a));m.scale.setScalar(.45+Math.random()*1.25);nodes.add(m)}
const count=innerWidth<700?430:950,pos=new Float32Array(count*3);for(let i=0;i<count;i++){const r=6+Math.random()*16,a=Math.random()*Math.PI*2,p=Math.acos(2*Math.random()-1);pos[i*3]=r*Math.sin(p)*Math.cos(a);pos[i*3+1]=r*Math.cos(p)*.65;pos[i*3+2]=r*Math.sin(p)*Math.sin(a)-5}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(pos,3));const particles=new THREE.Points(pg,new THREE.PointsMaterial({color:0x8ba3cd,size:.024,transparent:true,opacity:.52,sizeAttenuation:true,depthWrite:false}));scene.add(particles);
world.add(new THREE.Mesh(new THREE.SphereGeometry(1.68,48,48),new THREE.MeshBasicMaterial({color:0x6a9cff,transparent:true,opacity:.018,side:THREE.BackSide})));world.add(new THREE.Mesh(new THREE.SphereGeometry(1.82,24,18),new THREE.MeshBasicMaterial({color:0x8fdacb,wireframe:true,transparent:true,opacity:.033})));
scene.add(new THREE.HemisphereLight(0xb9cbff,0x06100f,1.45));const key=new THREE.PointLight(0xa8baff,42,18,2);key.position.set(4.5,5,6);scene.add(key);const rim=new THREE.PointLight(0x6dffd3,54,16,2);rim.position.set(-3.5,-2.4,4);scene.add(rim);const back=new THREE.PointLight(0x4267ff,34,16,2);back.position.set(4,-1,-5);scene.add(back);
const pointer=new THREE.Vector2(),target=new THREE.Vector2(),down={v:false,x:0,y:0},drag=new THREE.Vector2();addEventListener('pointermove',e=>{target.x=(e.clientX/innerWidth-.5)*2;target.y=(e.clientY/innerHeight-.5)*2;if(down.v){drag.x+=(e.clientX-down.x)*.0028;drag.y+=(e.clientY-down.y)*.0028;down.x=e.clientX;down.y=e.clientY}});addEventListener('pointerdown',e=>{down.v=true;down.x=e.clientX;down.y=e.clientY});addEventListener('pointerup',()=>down.v=false);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,clock=new THREE.Clock();function animate(){const t=clock.getElapsedTime();pointer.lerp(target,.035);if(!reduced){world.rotation.y=t*.075+pointer.x*.13+drag.x;world.rotation.x=Math.sin(t*.22)*.055-pointer.y*.09+drag.y;core.rotation.y=-t*.11;inner.rotation.x=t*.18;inner.rotation.y=-t*.14;ribbons[0].rotation.z+=.00045;ribbons[1].rotation.y-=.00035;ribbons[2].rotation.x+=.00025;nodes.rotation.y=-t*.035;particles.rotation.y=t*.004;camera.position.x=.8+pointer.x*.22;camera.position.y=.25-pointer.y*.16;camera.lookAt(innerWidth<760?new THREE.Vector3(.6,1.15,0):new THREE.Vector3(1.1,0,0))}composer.render();requestAnimationFrame(animate)}animate();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.35:1.75));renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);world.position.set(innerWidth<760?1.55:2.75,innerWidth<760?1.8:.2,0)});
setTimeout(()=>document.getElementById('loading').classList.add('hide'),500);
const reveals=[...document.querySelectorAll('.reveal')];const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});reveals.forEach(x=>io.observe(x));
const sections=[...document.querySelectorAll('section[id]')],navItems=[...document.querySelectorAll('.navlinks a[href^="#"]')];const spy=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){navItems.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}})},{rootMargin:'-35% 0px -55% 0px',threshold:0});sections.forEach(s=>spy.observe(s));
const frags=[...document.querySelectorAll('.fragment')],hubCards=[...document.querySelectorAll('.hub-card')];addEventListener('scroll',()=>{if(reduced)return;const y=scrollY;frags.forEach((el,i)=>el.style.translate=`0 ${Math.sin(y*.0015+i)*8}px`);hubCards.forEach((el,i)=>el.style.translate=`0 ${Math.sin(y*.0012+i*.8)*5}px`)},{passive:true});
